server:
  listen: 8000
  workers: 4
  
  upstreams:
    - id: node1
      url: http://localhost:8001

    - id: node2
      url: http://localhost:8002

    - id: node3
      url: http://localhost:8003

  headers:
    - key: x-forward-for
      value: '$ip'

    - key: Authorization
      value: 'Bearer xyz'

  rules:
    - path: /
      upstreams:
        - node1
 
    - path: /user
      upstreams:
        - node1
        - node2

    - path: /admin
      upstreams: 
        - node1
        - node2
        - node3
